### ISSUE TITLE
Check for updates - Stuck in loop

### ISSUE THREAD

**Issue by DisasterIncarnate** [jurassicplayer/decky-autoflatpaks#7]
SteamOS - Stable
DeckyLoader - Stable

Previously used to work, until the last stable update to steam-os (for me at least), now AutoflatPak's constantly searches for updates, messages the results via toast message, then immediatly loops back to searching/reporting and never actually gets to update, have to uninstall due to the toast message spamming up and making sounds non stop.

My other decky plugins seem to be working ok, so not sure whats gone wrong.

**Comment by jurassicplayer** [comment]
I'm not entirely sure what the issue is, or at least, I can't reproduce it with a simple change to Stable versions of SteamOS and DeckyLoader, but maybe you could check if the config (`~/homebrew/settings/decky-autoflatpaks/settings.json`) maybe has bad values like `null` or `None`. Alternatively, maybe just delete the config file and see if that fixes the issue (hopefully, otherwise I might need a little more information about what is going on).

**Comment by DisasterIncarnate** [comment]
you sir are a legend, you are right i looked in that json and for some weird reason "update interval" had no value, not sure how that happened as the only options i recall messing with was unattended updates, but just incase anything else was wrong/missing i deleted the file and now after a reboot its working as intended :D  many thanks.

**Comment by jurassicplayer** [comment]
Oh, well that was probably some failing of my coding in trying to migrate settings to the right spot.
